/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.iam.deep;import jakarta.persistence.*;import jakarta.validation.constraints.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;import java.time.*;import java.util.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Service @Transactional(readOnly=true)public class DeepDomainService{private final EntityManager em;/**
                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                     */
public DeepDomainService(EntityManager e){em=e;}/**
                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                     */
public Dashboard dashboard(String tenantCode){var t=tenantByCode(tenantCode);return new Dashboard(view(t),identities(t.id),assignments(t.id),requests(t.id));}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public TenantView tenant(TenantRequest r){var t=new IamTenant(r.tenantCode(),r.name());em.persist(t);audit("CREATE_TENANT",r.tenantCode(),r.name());return view(t);}/**
                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                     */
@Transactional public TenantView activateTenant(Long id){var t=tenant(id);if(!"DRAFT".equals(t.status))throw conflict("只有草稿租户可以启用");t.status="ACTIVE";audit("ACTIVATE_TENANT",t.tenantCode,t.name);return view(t);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public IdentityView identity(Long tenantId,IdentityRequest r){var t=tenant(tenantId);active(t);var i=new IamIdentity(tenantId,r.username(),r.displayName(),r.department(),r.mfaEnabled());em.persist(i);audit("CREATE_IDENTITY",r.username(),r.department());return view(i);}/**
                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                              */
@Transactional public RoleView role(Long tenantId,RoleRequest r){var t=tenant(tenantId);active(t);var role=new IamRoleDefinition(tenantId,r.roleCode(),r.name(),normalize(r.permissions()),r.privileged());em.persist(role);audit("CREATE_ROLE",r.roleCode(),role.permissions);return view(role);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public RequestView request(AccessRequestInput r){var i=identity(r.identityId());var role=role(r.roleId());if(!i.tenantId.equals(role.tenantId))throw bad("身份与角色不属于同一租户");if(r.validUntil().isBefore(LocalDate.now()))throw bad("授权有效期不能早于当前日期");var x=new IamAccessRequest(r.requestNo(),i.id,role.id,r.reason(),r.validUntil());em.persist(x);audit("REQUEST_ACCESS",x.requestNo,role.roleCode);return view(x);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public RequestView review(Long id,ReviewRequest r){var x=request(id);if(!"PENDING_APPROVAL".equals(x.status))throw conflict("访问申请状态不可审批");if(!r.approved()){x.status="REJECTED";x.reviewNote=r.note();return view(x);}var i=identity(x.identityId);var role=role(x.roleId);if(role.privileged&&!i.mfaEnabled)throw conflict("特权角色要求身份先启用MFA");Set<String> requested=split(role.permissions);var current=em.createQuery("select r from IamRoleDefinition r where r.id in(select a.roleId from IamAccessAssignment a where a.identityId=:i and a.status='ACTIVE')",IamRoleDefinition.class).setParameter("i",i.id).getResultList();Set<String> existing=new HashSet<>();current.forEach(z->existing.addAll(split(z.permissions)));if(conflictPermissions(existing,requested))throw conflict("访问申请触发职责分离冲突");em.persist(new IamAccessAssignment(i.id,role.id,x.validUntil));x.status="APPROVED";x.reviewNote=r.note();audit("GRANT_ACCESS",x.requestNo,role.roleCode);return view(x);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public AssignmentView revoke(Long id,RevokeRequest r){var a=assignment(id);if(!"ACTIVE".equals(a.status))throw conflict("授权已失效");a.status="REVOKED";a.revokedAt=LocalDateTime.now();audit("REVOKE_ACCESS",String.valueOf(id),r.reason());return view(a);}/**
                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                          */
@Transactional public int expire(LocalDate asOf){var list=em.createQuery("select a from IamAccessAssignment a where a.status='ACTIVE' and a.validUntil<:d",IamAccessAssignment.class).setParameter("d",asOf).getResultList();list.forEach(a->{a.status="EXPIRED";a.revokedAt=LocalDateTime.now();});return list.size();}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private boolean conflictPermissions(Set<String>a,Set<String>b){Set<String>all=new HashSet<>(a);all.addAll(b);return all.contains("PAYMENT_CREATE")&&all.contains("PAYMENT_APPROVE")||all.contains("USER_ADMIN")&&all.contains("AUDIT_REVIEW");}/**
                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                 */
private String normalize(String p){return String.join(",",split(p));}/**
                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                      */
private Set<String>split(String p){if(p==null||p.isBlank())return Set.of();return new HashSet<>(Arrays.stream(p.split(",")).map(String::trim).filter(x->!x.isBlank()).toList());}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
private void active(IamTenant t){if(!"ACTIVE".equals(t.status))throw conflict("租户未启用");}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               */
private IamTenant tenant(Long id){var x=em.find(IamTenant.class,id);if(x==null)throw missing("租户不存在");return x;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               */
private IamTenant tenantByCode(String c){return em.createQuery("select t from IamTenant t where t.tenantCode=:c",IamTenant.class).setParameter("c",c).getResultStream().findFirst().orElseThrow(()->missing("租户不存在"));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
private IamIdentity identity(Long id){var x=em.find(IamIdentity.class,id);if(x==null)throw missing("身份不存在");return x;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
private IamRoleDefinition role(Long id){var x=em.find(IamRoleDefinition.class,id);if(x==null)throw missing("角色不存在");return x;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
private IamAccessRequest request(Long id){var x=em.find(IamAccessRequest.class,id);if(x==null)throw missing("访问申请不存在");return x;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
private IamAccessAssignment assignment(Long id){var x=em.find(IamAccessAssignment.class,id);if(x==null)throw missing("授权不存在");return x;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
private void audit(String a,String n,String d){em.persist(new IamDomainAudit(a,n,d));}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private List<IdentityView>identities(Long t){return em.createQuery("select i from IamIdentity i where i.tenantId=:t",IamIdentity.class).setParameter("t",t).getResultList().stream().map(this::view).toList();}/**
                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                 */
private List<AssignmentView>assignments(Long t){return em.createQuery("select a from IamAccessAssignment a where a.identityId in(select i.id from IamIdentity i where i.tenantId=:t)",IamAccessAssignment.class).setParameter("t",t).getResultList().stream().map(this::view).toList();}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         */
private List<RequestView>requests(Long t){return em.createQuery("select r from IamAccessRequest r where r.identityId in(select i.id from IamIdentity i where i.tenantId=:t)",IamAccessRequest.class).setParameter("t",t).getResultList().stream().map(this::view).toList();}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private TenantView view(IamTenant t){return new TenantView(t.id,t.tenantCode,t.name,t.status);}/**
                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                 */
private IdentityView view(IamIdentity i){return new IdentityView(i.id,i.tenantId,i.username,i.displayName,i.department,i.mfaEnabled,i.status,i.version);}/**
                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                          */
private RoleView view(IamRoleDefinition r){return new RoleView(r.id,r.tenantId,r.roleCode,r.name,r.permissions,r.privileged,r.status);}/**
                                                                                                                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                 */
private RequestView view(IamAccessRequest r){return new RequestView(r.id,r.requestNo,r.identityId,r.roleId,r.reason,r.validUntil,r.status,r.reviewNote,r.version);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
private AssignmentView view(IamAccessAssignment a){return new AssignmentView(a.id,a.identityId,a.roleId,a.status,a.validUntil,a.grantedAt,a.revokedAt);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}/**
                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                              */
private ResponseStatusException conflict(String m){return new ResponseStatusException(HttpStatus.CONFLICT,m);}/**
                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                            */
private ResponseStatusException missing(String m){return new ResponseStatusException(HttpStatus.NOT_FOUND,m);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 public record TenantRequest(@NotBlank String tenantCode,@NotBlank String name){}/**
                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                  */
public record IdentityRequest(@NotBlank String username,@NotBlank String displayName,@NotBlank String department,boolean mfaEnabled){}/**
                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                        */
public record RoleRequest(@NotBlank String roleCode,@NotBlank String name,@NotBlank String permissions,boolean privileged){}/**
                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                    */
public record AccessRequestInput(@NotBlank String requestNo,@NotNull Long identityId,@NotNull Long roleId,@NotBlank String reason,@NotNull LocalDate validUntil){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
public record ReviewRequest(boolean approved,@NotBlank String note){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
public record RevokeRequest(@NotBlank String reason){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 */
public record TenantView(Long id,String tenantCode,String name,String status){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
public record IdentityView(Long id,Long tenantId,String username,String displayName,String department,boolean mfaEnabled,String status,long version){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
public record RoleView(Long id,Long tenantId,String roleCode,String name,String permissions,boolean privileged,String status){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     */
public record RequestView(Long id,String requestNo,Long identityId,Long roleId,String reason,LocalDate validUntil,String status,String reviewNote,long version){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
public record AssignmentView(Long id,Long identityId,Long roleId,String status,LocalDate validUntil,LocalDateTime grantedAt,LocalDateTime revokedAt){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
public record Dashboard(TenantView tenant,List<IdentityView>identities,List<AssignmentView>assignments,List<RequestView>requests){}
}
