/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.iam.deep;import cn.zhuatech.iam.common.ApiResponse;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;import java.time.*;/**
                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                            */
@RestController@RequestMapping("/api/admin/iam-ops")public class DeepAdminController{private final DeepDomainService s;/**
                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                   */
public DeepAdminController(DeepDomainService s){this.s=s;}/**
                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                             */
@PostMapping("/tenants")ApiResponse<?>tenant(@Valid@RequestBody DeepDomainService.TenantRequest r){return ApiResponse.ok(s.tenant(r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
@PostMapping("/tenants/{id}/activate")ApiResponse<?>activate(@PathVariable Long id){return ApiResponse.ok(s.activateTenant(id));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     */
@PostMapping("/tenants/{id}/roles")ApiResponse<?>role(@PathVariable Long id,@Valid@RequestBody DeepDomainService.RoleRequest r){return ApiResponse.ok(s.role(id,r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
@PostMapping("/access-requests/{id}/review")ApiResponse<?>review(@PathVariable Long id,@Valid@RequestBody DeepDomainService.ReviewRequest r){return ApiResponse.ok(s.review(id,r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
@PostMapping("/assignments/{id}/revoke")ApiResponse<?>revoke(@PathVariable Long id,@Valid@RequestBody DeepDomainService.RevokeRequest r){return ApiResponse.ok(s.revoke(id,r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
@PostMapping("/assignments/expire")ApiResponse<?>expire(@RequestParam LocalDate asOf){return ApiResponse.ok(s.expire(asOf));}}
