/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.iam;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.http.MediaType;import org.springframework.test.web.servlet.*;import java.util.regex.*;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.httpBasic;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@SpringBootTest@AutoConfigureMockMvc class DeepIamOpsTests{@Autowired MockMvc mvc;
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Test void tenantIdentityRoleAndAccessFormClosedLoop()throws Exception{long t=tenant("TEN-1");admin("/api/admin/iam-ops/tenants/"+t+"/activate","{}");long i=id(post("/api/iam-ops/tenants/"+t+"/identities","{\"username\":\"alice\",\"displayName\":\"张三\",\"department\":\"财务部\",\"mfaEnabled\":true}").andReturn());long r=id(admin("/api/admin/iam-ops/tenants/"+t+"/roles","{\"roleCode\":\"FIN-CREATE\",\"name\":\"付款制单\",\"permissions\":\"PAYMENT_CREATE\",\"privileged\":true}").andReturn());long q=id(post("/api/iam-ops/access-requests","{\"requestNo\":\"AR-1\",\"identityId\":"+i+",\"roleId\":"+r+",\"reason\":\"岗位职责\",\"validUntil\":\"2027-01-01\"}").andReturn());admin("/api/admin/iam-ops/access-requests/"+q+"/review","{\"approved\":true,\"note\":\"审批通过\"}").andExpect(jsonPath("$.data.status").value("APPROVED"));}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Test void privilegedRoleRequiresMfaAndSodConflictIsBlocked()throws Exception{long t=tenant("TEN-2");admin("/api/admin/iam-ops/tenants/"+t+"/activate","{}");long i=id(post("/api/iam-ops/tenants/"+t+"/identities","{\"username\":\"bob\",\"displayName\":\"李四\",\"department\":\"财务部\",\"mfaEnabled\":false}").andReturn());long r=id(admin("/api/admin/iam-ops/tenants/"+t+"/roles","{\"roleCode\":\"ADMIN\",\"name\":\"特权管理\",\"permissions\":\"USER_ADMIN\",\"privileged\":true}").andReturn());long q=id(post("/api/iam-ops/access-requests","{\"requestNo\":\"AR-2\",\"identityId\":"+i+",\"roleId\":"+r+",\"reason\":\"临时管理\",\"validUntil\":\"2027-01-01\"}").andReturn());admin("/api/admin/iam-ops/access-requests/"+q+"/review","{\"approved\":true,\"note\":\"尝试批准\"}").andExpect(status().isConflict());}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Test void operatorCannotUseAdminEndpoints()throws Exception{mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post("/api/admin/iam-ops/tenants").with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"tenantCode\":\"NO\",\"name\":\"越权\"}")).andExpect(status().isForbidden());}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 long tenant(String c)throws Exception{return id(admin("/api/admin/iam-ops/tenants","{\"tenantCode\":\""+c+"\",\"name\":\"知华科技租户\"}").andReturn());}/**
                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                     */
ResultActions post(String u,String b)throws Exception{return mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post(u).with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content(b));}/**
                                                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                         */
ResultActions admin(String u,String b)throws Exception{return mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post(u).with(httpBasic("admin","admin123")).contentType(MediaType.APPLICATION_JSON).content(b));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
long id(MvcResult r)throws Exception{var m=Pattern.compile("\"id\":(\\d+)").matcher(r.getResponse().getContentAsString());Assertions.assertTrue(m.find());return Long.parseLong(m.group(1));}}
